### ISSUE TITLE
Missing lvis_v1_train_norare_cat_info.json

### ISSUE THREAD

**Issue by ma-siddiqui** [hanoonaR/object-centric-ovd#3]
While running the code, I faced  error

[Errno 2] No such file or directory: 'datasets/lvis/lvis_v1_train_norare_cat_info.json'
 Please advise where can I download it?

Thanks,

**Comment by hanoonaR** [comment]
Hi @ma-siddiqui,

Kindly find the instructions to prepare the datasets for training on LVIS v1.0 at the [LVIS Open Vocabulary](https://github.com/hanoonaR/object-centric-ovd/blob/main/docs/DATASETS.md#lvis-open-vocabulary) section in the datasets readme. The annotations required, including `lvis_v1_train_norare_cat_info.json` can be downloaded from [here](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EjaR4-EQFmVNhaYmsJhbwKMBciHdSFd8Z2J7byTplHAURA?e=tbzhUM) as explained in [DATASETS.md](https://github.com/hanoonaR/object-centric-ovd/edit/main/docs/DATASETS.md).

Thank you.

**Comment by hanoonaR** [comment]
Hi @ma-siddiqui,

In order to prepare `lvis_v1_train_norare_cat_info.json` yourself, you will need to prepare the rare categories filtered annotation, `lvis_v1_train_norare.json` (details explained in [DATASETS.md](https://github.com/hanoonaR/object-centric-ovd/edit/main/docs/DATASETS.md)). The command is, 

`python tools/get_lvis_cat_info.py --ann datasets/lvis/lvis_v1_train_norare.json`


Thank you.
